openapi: 3.0.3
info:
  title: 2024-CC-A docs
  version: 0.0.1
paths:
  /ping:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
  /analyze_image:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
            example:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
